#ifndef STYIO_CONFIG_NANO_PROFILE_HPP
#define STYIO_CONFIG_NANO_PROFILE_HPP

#ifndef STYIO_NANO_BUILD
#define STYIO_NANO_BUILD 0
#endif

#ifndef STYIO_NANO_PROFILE_NAME
#define STYIO_NANO_PROFILE_NAME "full"
#endif

#ifndef STYIO_NANO_PROFILE_SOURCE
#define STYIO_NANO_PROFILE_SOURCE ""
#endif

#ifndef STYIO_NANO_ENABLE_MACHINE_INFO
#define STYIO_NANO_ENABLE_MACHINE_INFO 1
#endif

#ifndef STYIO_NANO_ENABLE_DEBUG_CLI
#define STYIO_NANO_ENABLE_DEBUG_CLI 1
#endif

#ifndef STYIO_NANO_ENABLE_AST_DUMP_CLI
#define STYIO_NANO_ENABLE_AST_DUMP_CLI 1
#endif

#ifndef STYIO_NANO_ENABLE_STYIO_IR_DUMP_CLI
#define STYIO_NANO_ENABLE_STYIO_IR_DUMP_CLI 1
#endif

#ifndef STYIO_NANO_ENABLE_LLVM_IR_DUMP_CLI
#define STYIO_NANO_ENABLE_LLVM_IR_DUMP_CLI 1
#endif

#ifndef STYIO_NANO_ENABLE_LEGACY_PARSER
#define STYIO_NANO_ENABLE_LEGACY_PARSER 1
#endif

#ifndef STYIO_NANO_ENABLE_PARSER_SHADOW_COMPARE
#define STYIO_NANO_ENABLE_PARSER_SHADOW_COMPARE 1
#endif

#ifndef STYIO_NANO_INCLUDE_PIPELINE_CHECK
#define STYIO_NANO_INCLUDE_PIPELINE_CHECK 1
#endif

#ifndef STYIO_NANO_ENABLE_DICT_BACKEND_ORDERED_HASH
#define STYIO_NANO_ENABLE_DICT_BACKEND_ORDERED_HASH 1
#endif

#ifndef STYIO_NANO_ENABLE_DICT_BACKEND_LINEAR
#define STYIO_NANO_ENABLE_DICT_BACKEND_LINEAR 1
#endif

#endif  // STYIO_CONFIG_NANO_PROFILE_HPP
